### PR TITLE
Search By Title

### LINKED ISSUE #6: Fetch books from goodreads by name

### PR DESCRIPTION
**Pull request by ydidwania**
Queries the Goodreads Api for the given string and returns at most 5 books as a [JSON response](https://pastebin.com/qyXTKwDG)
Hopes to fix #6

### CODE REVIEW

**Comment by ydidwania** [comment]
I rebased this branch on the one for the isbn search. Hence the bad  commit  history :(

**Comment by CodeMaxx** [comment]
That's okay... we'll merge this PR in place of previous one since this contains all the changes

**Comment by CodeMaxx** [comment]
Can you give a sample of the output?

**Comment by ydidwania** [comment]
The sample output is provided in the 1st comment (linked to "JSON Response").
I just noticed it returns 6 books instead of 5. Should I reduce them or its fine?

**Comment by CodeMaxx** [comment]
6 is fine. What was the title you sent?

**Comment by ydidwania** [comment]
harry

**Comment by ydidwania** [comment]
The search by name api works fine now. The PR is ready to merge imo.

**Pull request merged**
